#!/usr/bin/env python3
"""
Example: Process mining with PM4Py integration.

This example demonstrates how to:
1. Generate pseudo event logs from scenario flows
2. Perform process mining (discovery + conformance)
3. Generate reports and save to disk

Run from project root:
    python examples/process_mining_example.py
or:
    python -m examples.process_mining_example
"""

import json
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.ai.process_miner import ProcessMiner, PseudoLogConverter, mine_scenarios
from app.ai.mining_reporter import MiningReporter


def example_1_single_scenario():
    """Mine a single scenario."""
    print("=" * 70)
    print("Example 1: Single Scenario Mining")
    print("=" * 70)

    # Pseudo event log (as would be generated by ScenarioFlow.generate_pseudo_event_log())
    pseudo_log = {
        "case_id": "scenario_create_order_1",
        "process_name": "Create Order",
        "domain": "Order",
        "events": [
            {"order": 1, "event_name": "Receive Order Request", "event_type": "ENTRY"},
            {"order": 2, "event_name": "Validate Order", "event_type": "PROCESS"},
            {"order": 3, "event_name": "Calculate Price", "event_type": "PROCESS"},
            {"order": 4, "event_name": "Check Inventory", "event_type": "DB"},
            {"order": 5, "event_name": "Save Order", "event_type": "DB"},
            {"order": 6, "event_name": "Publish Order Created Event", "event_type": "QUEUE"},
            {"order": 7, "event_name": "Return Order Response", "event_type": "ENTRY"},
        ],
    }

    # Create miner
    miner = ProcessMiner(
        scenario_id=pseudo_log["case_id"],
        scenario_name=pseudo_log["process_name"],
        domain=pseudo_log["domain"],
    )

    # Run mining
    result = miner.mine_from_pseudo_log(pseudo_log)

    # Print summary
    summary = miner.get_summary()
    print(json.dumps(summary, indent=2))

    # Generate markdown report
    markdown = MiningReporter.generate_markdown_report(result)
    print("\n" + markdown)

    return result


def example_2_multiple_scenarios():
    """Mine multiple scenarios using batch function."""
    print("\n" + "=" * 70)
    print("Example 2: Multiple Scenarios Mining")
    print("=" * 70)

    pseudo_logs = [
        {
            "case_id": "scenario_create_order_1",
            "process_name": "Create Order",
            "domain": "Order",
            "events": [
                {"order": 1, "event_name": "Receive Request", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Save", "event_type": "DB"},
            ],
        },
        {
            "case_id": "scenario_approve_payment_2",
            "process_name": "Approve Payment",
            "domain": "Payment",
            "events": [
                {"order": 1, "event_name": "Receive Payment", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate Amount", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Check Funds", "event_type": "EXTERNAL_API"},
                {"order": 4, "event_name": "Process Payment", "event_type": "EXTERNAL_API"},
                {"order": 5, "event_name": "Record Transaction", "event_type": "DB"},
            ],
        },
        {
            "case_id": "scenario_cancel_order_3",
            "process_name": "Cancel Order",
            "domain": "Order",
            "events": [
                {"order": 1, "event_name": "Receive Cancel Request", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate Cancelable Status", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Refund Payment", "event_type": "EXTERNAL_API"},
                {"order": 4, "event_name": "Update Order Status", "event_type": "DB"},
                {"order": 5, "event_name": "Send Cancellation Confirmation", "event_type": "QUEUE"},
            ],
        },
    ]

    # Batch mining
    results = mine_scenarios(pseudo_logs)

    # Print summaries
    for scenario_id, result in results.items():
        print(f"\n✓ {scenario_id}")
        if result.conformance:
            print(f"  Fitness: {result.conformance.fitness:.1%}")
            print(f"  Bottlenecks: {len(result.bottlenecks)}")

    return results


def example_3_save_reports(results: dict):
    """Save mining reports to disk."""
    print("\n" + "=" * 70)
    print("Example 3: Save Reports to Disk")
    print("=" * 70)

    output_dir = Path("./data/mining_reports")

    for scenario_id, result in results.items():
        paths = MiningReporter.save_reports(result, output_dir)
        print(f"\n✓ {scenario_id}")
        print(f"  Markdown: {paths['markdown']}")
        print(f"  JSON: {paths['json']}")

    print(f"\nAll reports saved to: {output_dir}")


def example_4_log_conversion():
    """Demonstrate PseudoLogConverter."""
    print("\n" + "=" * 70)
    print("Example 4: Pseudo Log Conversion")
    print("=" * 70)

    pseudo_log = {
        "case_id": "test_case_1",
        "events": [
            {"order": 1, "event_name": "Start", "event_type": "ENTRY"},
            {"order": 2, "event_name": "Process", "event_type": "PROCESS"},
            {"order": 3, "event_name": "End", "event_type": "ENTRY"},
        ],
    }

    # Convert to PM4Py format
    log = PseudoLogConverter.convert(pseudo_log)

    print(f"✓ Converted to PM4Py EventLog")
    print(f"  Traces: {len(log)}")
    print(f"  Events in first trace: {len(log[0])}")

    for i, event in enumerate(log[0]):
        print(f"    {i+1}. {event.get('concept:name')}")

    return log


def example_5_aggregate_mining():
    """Mine multiple logs as a single aggregate."""
    print("\n" + "=" * 70)
    print("Example 5: Aggregate Mining (Multiple Cases)")
    print("=" * 70)

    # Multiple pseudo logs (different cases)
    pseudo_logs = [
        {
            "case_id": "case_order_001",
            "events": [
                {"order": 1, "event_name": "Create", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Save", "event_type": "DB"},
            ],
        },
        {
            "case_id": "case_order_002",
            "events": [
                {"order": 1, "event_name": "Create", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Save", "event_type": "DB"},
            ],
        },
        {
            "case_id": "case_order_003",
            "events": [
                {"order": 1, "event_name": "Create", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate", "event_type": "PROCESS"},
                # Note: case_003 skips Save step (error case)
            ],
        },
    ]

    # Convert all to single EventLog
    log = PseudoLogConverter.convert_multiple(pseudo_logs)

    print(f"✓ Converted {len(pseudo_logs)} pseudo logs to single EventLog")
    print(f"  Total traces: {len(log)}")
    print(f"  Total events: {sum(len(t) for t in log)}")

    # Mine aggregate
    miner = ProcessMiner("aggregate_order_flow", "Order Flow (Aggregate)", "Order")
    # Note: aggregate mining not directly exposed in ProcessMiner yet
    # This is a placeholder for future enhancement
    print(f"  (Aggregate mining would discover common patterns across all cases)")

    return log


def main():
    """Run all examples."""
    print("\n")
    print("╔" + "=" * 68 + "╗")
    print("║ PM4Py Process Mining Integration Examples" + " " * 25 + "║")
    print("╚" + "=" * 68 + "╝")

    # Example 1: Single scenario
    result_1 = example_1_single_scenario()

    # Example 2: Multiple scenarios
    results_2 = example_2_multiple_scenarios()

    # Example 3: Save reports
    example_3_save_reports(results_2)

    # Example 4: Log conversion
    example_4_log_conversion()

    # Example 5: Aggregate mining setup
    example_5_aggregate_mining()

    print("\n" + "=" * 70)
    print("All examples completed!")
    print("=" * 70)
    print("\nNext steps:")
    print("1. Review mining reports in ./data/mining_reports/")
    print("2. Check fitness scores—values < 0.90 indicate unmodeled paths")
    print("3. Review bottlenecks for optimization opportunities")
    print("4. Compare discovered model against original BPMN")
    print("\nFor integration into pipeline, see: docs/PM4PY_INTEGRATION.md")


if __name__ == "__main__":
    main()
