#!/usr/bin/env python3
"""
Example: Flow statistics over pseudo event logs.

This example demonstrates how to:
1. Compute edge-frequency flow statistics from scenario pseudo event logs
2. Generate markdown/JSON reports and save them to disk

Note: the former pm4py-based mining (discovery + conformance) was removed
2026-06-06 — see docs/architecture/decisions.md "Pseudo Event Log Generation"
for the reversal record.

Run from project root:
    python examples/process_mining_example.py
"""

import json
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from ai_discovery.ai.process_miner import ProcessMiner, mine_scenarios
from ai_discovery.ai.mining_reporter import MiningReporter


def example_1_single_scenario():
    """Compute flow statistics for a single scenario."""
    print("=" * 70)
    print("Example 1: Single Scenario Flow Statistics")
    print("=" * 70)

    # Pseudo event log (as would be generated by ScenarioFlow.generate_pseudo_event_log())
    pseudo_log = {
        "case_id": "scenario_create_order_1",
        "process_name": "Create Order",
        "domain": "Order",
        "events": [
            {"order": 1, "event_name": "Receive Order Request", "event_type": "ENTRY"},
            {"order": 2, "event_name": "Validate Order", "event_type": "PROCESS"},
            {"order": 3, "event_name": "Calculate Price", "event_type": "PROCESS"},
            {"order": 4, "event_name": "Check Inventory", "event_type": "DB"},
            {"order": 5, "event_name": "Save Order", "event_type": "DB"},
            {"order": 6, "event_name": "Publish Order Created Event", "event_type": "QUEUE"},
            {"order": 7, "event_name": "Return Order Response", "event_type": "ENTRY"},
        ],
    }

    miner = ProcessMiner(
        scenario_id=pseudo_log["case_id"],
        scenario_name=pseudo_log["process_name"],
        domain=pseudo_log["domain"],
    )

    result = miner.mine_from_pseudo_log(pseudo_log)

    # Print summary
    summary = miner.get_summary()
    print(json.dumps(summary, indent=2))

    # Generate markdown report
    markdown = MiningReporter.generate_markdown_report(result)
    print("\n" + markdown)

    return result


def example_2_multiple_scenarios():
    """Compute flow statistics for multiple scenarios using the batch function."""
    print("\n" + "=" * 70)
    print("Example 2: Multiple Scenarios")
    print("=" * 70)

    pseudo_logs = [
        {
            "case_id": "scenario_create_order_1",
            "process_name": "Create Order",
            "domain": "Order",
            "events": [
                {"order": 1, "event_name": "Receive Request", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Save", "event_type": "DB"},
            ],
        },
        {
            "case_id": "scenario_approve_payment_2",
            "process_name": "Approve Payment",
            "domain": "Payment",
            "events": [
                {"order": 1, "event_name": "Receive Payment", "event_type": "ENTRY"},
                {"order": 2, "event_name": "Validate Amount", "event_type": "PROCESS"},
                {"order": 3, "event_name": "Check Funds", "event_type": "EXTERNAL_API"},
                {"order": 4, "event_name": "Process Payment", "event_type": "EXTERNAL_API"},
                {"order": 5, "event_name": "Record Transaction", "event_type": "DB"},
            ],
        },
    ]

    results = mine_scenarios(pseudo_logs)

    for scenario_id, result in results.items():
        print(f"\n✓ {scenario_id}")
        print(f"  Events: {result.event_count}")
        print(f"  Edges: {len(result.edge_frequencies)}")

    return results


def example_3_save_reports(results: dict):
    """Save flow-statistics reports to disk."""
    print("\n" + "=" * 70)
    print("Example 3: Save Reports to Disk")
    print("=" * 70)

    output_dir = Path("./data/mining_reports")

    for scenario_id, result in results.items():
        paths = MiningReporter.save_reports(result, output_dir)
        print(f"\n✓ {scenario_id}")
        print(f"  Markdown: {paths['markdown']}")
        print(f"  JSON: {paths['json']}")

    print(f"\nAll reports saved to: {output_dir}")


def main():
    """Run all examples."""
    example_1_single_scenario()
    results = example_2_multiple_scenarios()
    example_3_save_reports(results)

    print("\n" + "=" * 70)
    print("All examples completed!")
    print("=" * 70)


if __name__ == "__main__":
    main()
